server:
  port: 8083
spring:
  application:
    sagaqueue: order.saga.event.stream
  rabbitmq:
    hostname: 127.0.0.1
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:restaurant-order
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        order: 100
  amqp:
    exchange: events.fanout.exchange


