server:
  port: 8084
spring:
  application:
    name: command-restaurant
  datasource:
    url: jdbc:h2:mem:restaurant-restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100
  kafka:
#    client-id: restaurant-command
    default-topic: axon-events
    producer:
      retries: 5
      bootstrap-servers: localhost:9092
      transaction-id-prefix: restauranttx
    consumer:
      group-id: restaurant-command-group
      bootstrap-servers: localhost:9092
  distributed:
    enabled: true
  serializer:
    messages: xstream
  eventhandling:
    processors:
      restaurantordersaga:
        mode: tracking
        source: kafkaMessageSource
