server:
  port: 8081
spring:
  application:
    sagaqueue: courier.saga.event.stream
  rabbitmq:
    hostname: 127.0.0.1
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:restaurant-courier
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        courier: 100
        courierorder: 100
  amqp:
    exchange: events.fanout.exchange



